name: BuildAndPush

on:
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Begin pipeline
        run: echo Vamos la

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build src/ExampleLongPollingWithTaskCompletionSource.Api/

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME_DOCKER_HUB }}
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}  

      - name: Build and push Docker image
        run: |
          docker build src/ExampleLongPollingWithTaskCompletionSource.Api ${{ secrets.USERNAME_DOCKER_HUB }}/ExampleLongPollingWithTaskCompletionSource.Api:latest .
          docker push src/ExampleLongPollingWithTaskCompletionSource.Api ${{ secrets.USERNAME_DOCKER_HUB }}/ExampleLongPollingWithTaskCompletionSource.Api:latest

      

          
    

    
    
    
        
        
      
    
