name: BuildAndPush

on:
  push:
    branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Begin pipeline
        run: echo Vamos la
    
